name: sainte_app
description: "Supporting Your Journey"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  go_router: ^14.0.2
  supabase_flutter: ^2.9.1
  
  # UI dependencies
  flutter_svg: ^2.0.10+1
  
  # Utilities
  shared_preferences: ^2.0.15
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/svg/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter_28pt-Regular.ttf
    - family: InterBold
      fonts:
        - asset: assets/font/Inter_18pt-Bold.ttf
    - family: InterMedium
      fonts:
        - asset: assets/font/Inter_28pt-Medium.ttf